### ISSUE TITLE
Stepper: Import statements cause errors

### ISSUE THREAD

**Issue by leeyi45** [source-academy/js-slang#1223]
Running any code with an import statement in the stepper simply produces the output `error`

<img width="751" alt="image" src="https://user-images.githubusercontent.com/9127758/155869327-175e07ba-69db-4472-b629-7ae013470f86.png">

**Comment by martin-henz** [comment]
Instead of an error, the stepper should accommodate imported modules and display values created by modules in appropriate ways. For example, runes should be displayed within steps of the stepper:

import { heart, stack, show, red } from "rune"; show(stack(heart, red(heart)));
=>
show(stack(■,red(■)))
=>
show(stack(■, ■))
=>
show(■)
=>
■
In this case, the stepper would use the ■ symbol to represent any rune.

Of course even better would be a mini-version of the actual rune:

import { heart, stack, show, red } from "rune"; show(stack(heart, heart));
=>
show(stack(♥,red(♥)))
=>
show(stack(♥, ❤️))
=>
show(*)
=>
*
where * is the correct stack of heart.

**Comment by martin-henz** [comment]
In addition, every evaluation of "show" should lead to a display of the rune in the runes tab. This is already working in the environment visualizer.
