### ISSUE TITLE
How to organise Python and Scheme language parsers?

### ISSUE THREAD

**Issue by Fidget-Spinner** [source-academy/js-slang#1331]
Two CP3108 projects this semester are adding Python and Scheme parsers which translate those languages to Source/JS.

I would like to upload the code for the Python parser. However, I don't want to clutter up this repository. Should we create a subfolder and push it there, or should I create a separate repository under the SourceAcademy organisation, and install that as a package in js-slang?

I'm more inclined towards the second option. Since packages seem like a neat way to separate the concerns.

**Comment by salty-flower** [comment]
Personally, I like the second option better, too. For example, our source->ev3 compiler is hosted in a separate repository :)

**Comment by martin-henz** [comment]
Let's discuss this carefully. Once a decision is made, it's hard to reverse. I see pros and cons for a separate repository:
Pros: Simpler structure, neat separation of JS and Python, clean deployment
Cons: Duplication of components.

It might be worth duplicating components, because then they can cater well for the idiosyncrasies of the respective language without cluttering the implementation with runtime checks what language is being used.

So yea, I'm with you on this: It might be better to separate the two: js-slang and py-slang.

We might have a similar situation with the sicp repo: We might end up with sicp-js and sicpy repos.

**Comment by Fidget-Spinner** [comment]
We (the Python and Scheme) groups will probably meet @shenyih0ng to discuss this before the gathering on Tuesday.

**Comment by Fidget-Spinner** [comment]
Resolved: we shall place each parser into a separate npm package. Those packages shall be installed in js-slang and their output (an estree AST) shall be consumed by js-slang.
