### ISSUE TITLE
Use asynchronous GET requests / Replace `xmlhttprequest-ts` with `fetch` API for module loading

### ISSUE THREAD

**Issue by Yongbeom-Kim** [source-academy/js-slang#1348]
Continued from #1340 

# Problem
- Currently, `js-slang` uses the `xmlhttprequest-ts` package to make GET requests to retrieve module data.
- The [package](https://www.npmjs.com/package/xmlhttprequest-ts) has not had any updates/releases in the past 5 years, and it seems safe to say that this package should be deprecated in favour of something like `fetch` instead, as suggested by a contributor(?) https://github.com/hmoog/xmlhttprequest-ts/issues/6
- It's also worthy of noting that synchronous/blocking XMLHttpRequests (as is being done in js-slang) are [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests#synchronous_request)
- Well, it makes sense that the get request should be asynchronous/non-blocking?

# Proposal
- Refactor js-slang to load modules asynchronously (with async functions and promises)
- Replace all XMLHttpRequest GET requests with `fetch` requests
- Use top-level await to load modules (if needed)
  - I don't think this is a big issue, noting that top-level await is [supported on all browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#browser_compatibility)
  - This also requires bumping tsconfig.json to:
```
{
  "compilerOptions": {
    "module": "esnext" (or system),
    "target": "es2017",
}
```

**Comment by leeyi45** [comment]
As part of this, I'm thinking we delegate loading of tabs to the frontend. Tabs are a frontend only concept, so I don't think it makes sense for js-slang to do the loading.

**Comment by RichDom2185** [comment]
I would say this is an issue of high enough priority; I will pin it to the top of our issues list.

**Comment by leeyi45** [comment]
This transition is actually almost complete. Most of the features surrounding module loading are asynchronous, namely
- Loading the module manifest
- Module Documentation
- Transpiler
- Stepper

The two remaining areas of concern are:
- The EC-Evaluator: Refer to (my comment on this)[https://github.com/source-academy/js-slang/pull/1428#issuecomment-1662237400]
- The regular interpreter, which is due to be removed as per #1476
Both of which still require the synchronous versions
