### ISSUE TITLE
Duplication of Source error messages on frontend

### ISSUE THREAD

**Issue by zhaojj2209** [source-academy/js-slang#1349]
This bug seems to have been introduced after bumping js-slang version on frontend, likely has to do with the refactoring done on #1343. One possible explanation is that the frontend is calling `parse` multiple times, resulting in errors being duplicated.
![image](https://user-images.githubusercontent.com/54243224/216061455-0a3fdcf6-9411-421f-b6e4-3b595505a2ad.png)

**Comment by ianyong** [comment]
Thanks for spotting this bug!

In #1343, I refactored the control flow of the Source runner such that it is more streamlined and readable. In the process, I also removed the resetting of the `errors` array on the `context` object that is passed around since the refactored control flow does not require it - assuming that a fresh context is passed into `runInContext` (i.e., no errors).

However, it seems that the frontend calls `parse` before calling `runInContext`, which results in the `context` being passed into `runInContext` inheriting any errors from the previous call to `parse`.

@martin-henz Should ensuring that the `errors` array being empty on the `context` object be the responsibility of `js-slang`, or the users of `js-slang` (i.e., frontend in this case)? In other words, should the `errors` array reflect all errors encountered throughout all runs which the `context` is involved in, or just the latest run? The former would imply that `js-slang` should not reset the `errors` array, while the latter implies that `js-slang` should.

**Comment by ianyong** [comment]
Actually, the more I think about this, something doesn't add up here. Why is the frontend even calling the `parse` function? It should let js-slang handle the parsing when running the program. This breaks abstraction and doesn't translate well into the multi-file program context.

**Comment by ianyong** [comment]
> Actually, the more I think about this, something doesn't add up here. Why is the frontend even calling the `parse` function? It should let js-slang handle the parsing when running the program. This breaks abstraction and doesn't translate well into the multi-file program context.

I will fix this bug first, then deal with the refactoring in a later PR.

**Comment by martin-henz** [comment]
Yes, I agree. The frontend should have no business calling parse.
