### ISSUE TITLE
CSE Machine: cannot handle binary search with loop

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1498]
https://share.sourceacademy.nus.edu.sg/0buyr

gives no response.

This variant gives a strange error in the REPL:
https://share.sourceacademy.nus.edu.sg/0buyr
<img width="434" alt="Screenshot 2023-10-18 at 10 46 45 AM" src="https://github.com/source-academy/js-slang/assets/30220768/385b51b3-e08c-40a0-b885-f98752e57824">

**Comment by martin-henz** [comment]
The problem lies in the "else if" construct. Putting a block around the nested "if" will lead to success: https://share.sourceacademy.nus.edu.sg/emmdc

**Comment by NhatMinh0208** [comment]
The cause is in the functions `hasContinueStatement`, `hasReturnStatement` and `hasBreakStatement`. These functions expect a block statement and recurse into `if` statements, which fails on `else if` constructs since they nest an `if` statement inside an `if` statement.

A modification to these functions to handle these cases should work.
