### ISSUE TITLE
CSE Machine: validation is skipped

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1502]
This program `() => c;` should give 
`Line 1: Name c not declared.`
but currently evaluates without error.

**Comment by NhatMinh0208** [comment]
The root cause of this appears to be that no validation is performed in the CSE machine at all - for example, this program also evaluates without error:
```{lang=js}
const a=1;
if (false) {
    c;
}
else {
    a;
}
```
https://share.sourceacademy.org/novalincse
I think we should borrow the `checkForUndefinedVariables` function from the stepper to accomplish this.
