### ISSUE TITLE
Potential WebWorker Solution?

### ISSUE THREAD

**Issue by openorclose** [source-academy/js-slang#218]
# TL;DR

https://source.openorclo.se/

I created a barebones "transpiler" here. Currently you have to manually transpile your code (:.

Most importantly, you can try running the "infinite" preset. Note that it doesn't hang the browser since the code runs on a separate thread, and a second later the output is returned.

I have the setglobal and getglobal preset just as a proof of concept that we can save/retrieve variables.

-----
# Motivations

Hanging the browser, no matter how short a period of time, makes for a horrible user experience. 
We should try and solve this.

Even in the interpreter, builtins still cause these hangings sometimes. 

Ultimately, it would be great if we can move the interpreter and native evaller out into a web worker.

-------

# Limitations

- Functions cannot be passed to and from WebWorkers. Which is just as well, since we need a new library loading mechanism anyway, and if we decide to pass in libraries as strings and then (eval them in native) / (interpret them in the interpreter) this becomes a non-issue.
- Webworkers do not allow interop with the DOM. `show`, `display` etc all require the dom. Potentially, we can create a wrapper that returns some intermediate value, and then call the real `show` or `display` function in the main thread.
- Non-primitives that are passed to/from workers are copied (example: give an object `{a:1}` to a worker and let the worker return the same thing then compare them with `===`, it evaluates to false) , and furthermore as mentioned functions cannot be passed back into the main thread. This means that any updating of the context (saving global variables etc) needs to be done on the worker thread itself, and it is impossible to gain knowledge about it from the main thread. Therefore, If debugger/inspector requires non-JSON-stringifiable information it would not be possible to get it using this method.
- Obviously, it would be horrible to try to write tests and test it in this repo, and I'm unsure if it can be solely done in cadet-frontend. If not, there would be very tight coupling between the two repos, which is undesirable.

# Conclusion

CP3108?

**Comment by thomastanck** [comment]
> Functions cannot be passed to and from WebWorkers.

As you've said, it's not really a problem and in my opinion it serves as a neat way to increase the security of js-slang at the same time. Now all potentially malicious code has to pass through the parser, even library functions.

> No interop with DOM.

I think this too isn't a big problem since `externalLib` is already abstracting away the user interface. We just need to add a WebWorker postMessage response in there (something like `{type: 'display', content: 'blah blah'}` or `{type: 'show', content: 'data:image/png;base64,iVBORw0KGgo ... AAAASUVORK5CYII='}`

> Non-primitives are copied.

I don't think this is an issue, I think expecting mutable shared memory in JS is a big code smell.

> Communication happens through JSON.

Definitely a limitation, but JSON is pretty strong as it is and many (real world) applications successfully use JSON in their RPCs.

> Tests.

I've successfully used a emulation layer for testing in Node before, to make the Worker interface available to both my backend and frontend code for consistency.

https://github.com/pgriess/node-webworker
https://github.com/audreyt/node-webworker-threads
https://github.com/avoidwork/tiny-worker

Some are more performant than others. As long as JSON-serializable data only is sent, there should be no problems, though I believe sending other types of data may be undefined behaviour rather than an error on some libraries (not sure if this has changed in the past couple years).

Using this library we can write the tests with the emulation layer and pray that they continue to work with browser WebWorkers.

**Comment by martin-henz** [comment]
Incidentally, Tobias and I are looking at Section 3.4 of the textbook, which covers concurrency. ES2017 feature SharedArrayBuffer in combination with web workers would allow us to implement some of the examples in the textbook. Would be fun to do some experiments with this and provide nice examples for concurrency control in JS.
[sicpjs.pdf](https://github.com/source-academy/js-slang/files/3328237/sicpjs.pdf)
(This includes PR "concurrency". Not merged yet.)

**Comment by btzy** [comment]
> Non-primitives that are passed to/from workers are copied

I think if your object implements [Transferable](https://developer.mozilla.org/en-US/docs/Web/API/Transferable) you could do a _move_ instead of _copy_.  That would be a constant-time operation and would probably preserve the semantics of `===`.  I think normal JavaScript objects implement Transferable.  So you could in theory move the object from the interpreter thread to the main thread, and then later move it back to the interpreter thread.

> Webworkers do not allow interop with the DOM. `show`, `display` etc all require the dom. Potentially, we can create a wrapper that returns some intermediate value, and then call the real `show` or `display` function in the main thread.

The interesting part is when the function needs a return value (e.g. `prompt`), and hence cannot be executed asynchronously.  To preserve the call stack in the worker, you will probably need to use the synchronisation primitives provided by SharedArrayBuffer unless you do busy waiting.  SharedArrayBuffers used to work, but unfortunately now they only work on Chrome due to Spectre.

**Comment by btzy** [comment]
I believe SharedArrayBuffers are now also working on Firefox.

**Comment by martin-henz** [comment]
I'm just afraid that the extra complexity in the system will make it hard to maintain and improve it. 

Should we wait until JavaScript has proper concurrency, and otherwise just live with the timeout hack?

**Comment by martin-henz** [comment]
Moving this to the wiki
