### ISSUE TITLE
LANG: Non-integer number keys in arrays

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#279]
are currently supported

<img width="205" alt="Screenshot 2019-07-07 at 6 31 49 PM" src="https://user-images.githubusercontent.com/30220768/60767127-89b7f480-a0e5-11e9-87cc-08bfbe0b6350.png">

but the §3 specs say that keys must be integers.

My suggestion: keep the language specs simple, and allow *any number* to be used as key. 

So I propose that we adapt the specs to the current implementation.

What do you all think?

**Comment by thomastanck** [comment]
Hm, I don't agree, since array is meant to be a way to store a sequential list of values (possibly with "holes"). This link seems to explain the JS specs for this: https://2ality.com/2012/12/arrays.html

----

The ECMAScript specification has a very narrow definition for what property keys are considered array indices. A string s is an array index if and only if:
s, parsed as an unsigned 32 bit integer and converted to string is equal to s.
s, converted to integer, is smaller than 232−1 (the maximum length).
Thus, if compared numerically, an array index s must be within the range
0 ≤ s < 232−1

----

Storing something with non-integer keys makes javascript treat it as a property and can't be considered part of the array.

I think should fix the interpreter instead, and for the specs I think the word "number" can be replaced with "non-negative integer"?

**Comment by martin-henz** [comment]
> Storing something with non-integer keys makes javascript treat it as a property and can't be considered part of the array. I think should fix the interpreter instead, and for the specs I think the word "number" can be replaced with "non-negative integer"?

Two issues with this:

(1) What is an integer?

If we follow your proposal, we would need to define what we mean by "integer". So far, we have avoided that. Would you want to restrict these "integers" to be greater or equal to 0 and less than 2^32-1? That's strange because the number of precisely representable integers in 64 bit floating point numbers is much larger.

(2) Who pays the price?

Our current implementation already pays a price on top of JavaScript arrays, with an additional runtime check. Your proposal makes array access even more expensive, by adding a check for whatever notion of integer we would settle on.

My proposal is simply following the type that we have already defined: is_number. When it comes to efficiency we can tell the students that it's best to stick to small integers as keys.

**Comment by thomastanck** [comment]
I think allowing non-integer numbers goes against what an array is supposed to be, though. For example in C, arrays require integer keys because of how they fundamentally work. If we allow arbitrary numbers here then they function more as "objects with some restriction on the keys" as opposed to actual arrays.

Here's an example showing the problem of having keys refer to properties of the array object as opposed to actually being in the array:

![maim9999](https://user-images.githubusercontent.com/829070/60782106-d51ae300-a177-11e9-998d-40ecb2c2da3d.png)

As for the issues:

    (1) What is an integer?

I think we just have to say it's defined as "an integer between 0 and 2^32-1", as per the article. It's not that strange if think of how browsers originally implemented them (which then affected how the spec was written).

    (2) Who pays the price?

I don't believe these checks are that expensive, nor do I think that it's that important of a problem. Since all these checks are put in a single function in utils/rttc.tsc, most of the runtime cost probably comes from the cost of the function call itself, after JIT kicks in. Of course, the only way to be sure is to run benchmarks on this.

Also as per the article, I've implemented the test in my branch (#282) as follows:

![maim9954](https://user-images.githubusercontent.com/829070/60782432-2c6d8300-a179-11e9-86fb-96eff996bf17.png)

**Comment by martin-henz** [comment]
Hmm, even with these integers, we wont have "real" arrays. For example, we don't expect the following program to allocate 4 GB of memory:

https://sourceacademy.nus.edu.sg/playground#chap=4&ext=NONE&prgrm=MYewdgzgLgBARgSwOYH0FigUyZgTjAXhgFsBDKACxQAcQB3ACgCYAaGAZiYEoYBaGJgG4AUMNCRYxAJ4pSuXKSmEYAbQC6I4dNnzFKxKnRYcuNcoNoM2PCKA

So the bigger lesson would be: Use the data structure as a random-access data structure, and assume constant access time, and reasonable space consumption. Leave the details to the implementers of the language.

**Comment by thomastanck** [comment]
In that case, how do we explain the return value of array_length when the array has floating point keys? It seems weird to me that it doesn't get counted as part of the length, and doesn't get iterated over with apply_in_underlying_javascript.

**Comment by openorclose** [comment]
We could take it a step further,.and only allow the setting of the properties 0 to the length of the array, so that no holes are allowed.

**Comment by martin-henz** [comment]
apply_in_underlying_javascript: How does that work? Wow, is that a loophole? How do you iterate over an array using apply_in_underlying_javascript?

**Comment by martin-henz** [comment]
I guess, the function array_length is of practical use. We should keep it.

**Comment by martin-henz** [comment]
We could define it like this:

array_length(a): returns the highest integer i used so far as key in array assignment a[i] = ...;, where 0 =< i < 2^32-1. This function is useful in programs that use only integer keys in the range 0 =< i < 2^32-1, a restriction that is common in other programming languages.

**Comment by martin-henz** [comment]
In your version, the definition would be slightly simpler:

array_length(a): returns the highest integer i used so far as key in array assignment a[i] = ...;, or 0, if a is [] and no assignment has been made yet.

**Comment by martin-henz** [comment]
> We could take it a step further,.and only allow the setting of the properties 0 to the length of the array, so that no holes are allowed.

That would be super-weird: To use a large array, you would have to initialize it using a process of linear time complexity!

**Comment by thomastanck** [comment]
I don't think he means initialisation but rather restricting it so it's used like a fixed-length array instead. Then you'd probably need to declare the array size somehow on initialisation.

**Comment by martin-henz** [comment]
I changed my mind on this: You are right: We should teach arrays as properly as JavaScript allows us, which is following your proposal.

Let's introduce a "type" called array index. An integer is an array index if it is larger than or equal to 0 and smaller than 2^32 - 1.

**Comment by martin-henz** [comment]
Todo: fix documentation
