### ISSUE TITLE
Negative zero?

### ISSUE THREAD

**Issue by SwampertX** [source-academy/js-slang#334]
`1 / -Infinity` evaluates to `0` in source, but is evaluated to `-0` in node.

**Comment by martin-henz** [comment]
The substituter surpassing NATIVE in ECMAScript compliance!

**Comment by martin-henz** [comment]
This is a bug in all three runtime systems: native, interpreter and stepper.

Not very important, though.

**Comment by btzy** [comment]
My guess is that this is not a bug.  This behaviour also occurs in Source §1 WebAssembly, which uses a totally different backend.

`1/(1/-Infinity);` returns `-Infinity`, so it seems that the sign is actually preserved.  I think the issue is that `(-0).toString()` gives "0", but prehaps this is expected as per the ECMAScript spec.

**Comment by martin-henz** [comment]
Vaguely remember this creeping up some time back. Yes, there is a negative zero in IEEE 754. ECMAScript basically adopts IEEE 754, but there are some tricky issues. Joey Chen might have some insights here. @JoeyChenSmart

**Comment by JoeyChenSmart** [comment]
Sorry, can't thing of anything more I can add here.

**Comment by btzy** [comment]
No, the issue is not IEEE 754.  We do have a negative zero, and it is represented correctly in js-slang and wasm.  The issue here is regarding the stringify() function, and what it means to "returns a string that represents the value v, using a notation that is consistent with JSON".  Specifically, it's about whether `stringify(-0)` should return 0.

It seems that the [JSON standard](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) does not explicitly state how `-0` should be encoded in JSON.  Chrome however thinks that `JSON.stringify(-0)` should return "0".  If Chrome is correct, then this is not a bug.

**Comment by btzy** [comment]
There is however another issue here, relating to the difference between `JSON.stringify(num)` and `num.toString()`  They are not fully equivalent.  The latter is used in the implementation of `stringify()` and `display()`, while the former is mandated by the Source spec.

The `NaN` and the `Infinity` values are not permitted in JSON, but they have a well-defined result in `.toString()`.  This leads to a discrepancy between the Source spec and the actual implementation.
