### ISSUE TITLE
SUBST: not terminating

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#367]
```
function factorial(n) {
    return n === 1 
           ? 1
           : 1 + factorial(n - 1);
}

factorial(1000); // barely works

factorial(10000); // frontend does not return (browser tab crashes)
```

We need a solution similar to the NATIVE system: some graceful degradation, with a timeout and nice error message.

**Comment by thomastanck** [comment]
Super brief thoughts, ask me for details when we actually start working on this.

I think the subst steps should be generated on the fly with some amount of caching. the caching should probably be done via remembering the "nearby steps" as well as "faraway steps" in some suitable ratio. You want to save the faraway nodes equally spaced, but since you're not generating the full list of steps, you have no idea how long the reductions are, and you won't know how often you want to save the "faraway nodes".

One idea is to generate a "depth" for each reduction step and form a skip list. Then using the skip list it should be easy to remember the k steps with the highest "depths" (of course, as we would need to remember everything in a particular depth, we may store more than k steps temporarily). When seeking backwards far enough, deleted steps can be regenerated easily by continuing off from the nearest cached step in the skip list

This may be overkill though.

**Comment by martin-henz** [comment]
this is handled in the current stepper
