### ISSUE TITLE
Limit === and !== to numbers and strings for Source §1 and §2

### ISSUE THREAD

**Issue by btzy** [source-academy/js-slang#389]
It seems that the spec for Source §2 (https://sicp.comp.nus.edu.sg/source/source_2.pdf) does not specify the behaviour of binary operators === and !== when the arguments are pairs.

If both the arguments are pairs, then there seems to be two possibilities:
1) Elementwise comparison (value semantics).
This seems reasonable, because Source does not have the notion of 'objects' that are held by reference (like JavaScript objects), and all its primitive types (strings, integers, booleans) have value semantics (this is not explicitly specified, but can be inferred since JavaScript primitives have value semantics).  But then there is a builtin equals() method for pairs, which would be redundant if this is the case.
2) Identity comparison (reference semantics).
This would be reasonable if pairs are to be viewed as JavaScript objects, which have reference semantics, especially if one has prior experience with JavaScript.  However, there seems to be no mention of JavaScript objects in the spec, and no mention of how pairs should be compared either.  Careful reading of the 'Deviations from JavaScript' section might suggest that Source must be interpretable as JavaScript code, which would only be possible with identity comparison.  Nonetheless, the spec does not specify whether pairs are JavaScript objects, so it isn't clear in any case.

I suggest the spec be made clearer on this.

**Comment by martin-henz** [comment]
Yes, indeed. This is an issue with the Source specs at the moment. The problem is that the computational model of §1 and §2 of SICP (substitution) does not explain sharing of data structures. The cleanest solution, I feel, would be to restrict === and !== to numbers and strings (and perhaps boolean values?). Any opinions, anyone?

**Comment by btzy** [comment]
I'm assuming that you mean `pair(1,2)===pair(1,2)` will now trap.  I think that solution has some issues. 
 Would heterogeneous comparison still work?  E.g.:
```
"2"===2; // currently returns false, but will it trap in your proposal?
```
If it traps, then that would be yet another deviation from JavaScript.  This kind of semantics aligns more towards statically typed languages.
If it still returns `false`, then there would be an inconsistency here.  Should `pair(1,2)===2` trap or return false?

-------

I think the underlying issue is that pairs currently have reference semantics (although not specified in the spec) even though that are meant to be used with value semantics.  E.g.

```
let s = "abcdefg";
do_something(s);
display(s); // Guaranteed to print "abcdefg"

let p = pair(1,2);
do_something(p);
display(p); // We can't tell what will be printed unless we know what `do_something` does
```
The above example shows that pairs are somehow "different" from strings and numbers.  I would propose to make pairs behave the same as strings and numbers - pairs should be passed/copied by value.  Then `===` and `!==` would have an "obvious" meaning - to perform element-wise comparison - and we also wouldn't need to break heterogeneous comparison.

**Comment by martin-henz** [comment]
The trouble, I feel, is that in Chapter 3, we are introducing a mental model that makes sharing explicit: the environment model, see Section 3.3.1.

Regarding "yet another deviation from JavaScript": Our stance here is that every Source program should behave according to the ECMAScript specs. That would still the case, if we exclude programs from Source which apply === in ways that we explicitly forbid.

I agree that we are moving into the direction of typed languages with these restrictions. That's not necessarily bad. I feel that it's healthy for the students to get an intuitive understanding of types, and to follow a type discipline, because many "real" programming language impose quite a strict type system, anyway.

Regarding:

Would heterogeneous comparison still work? E.g.:
"2"===2; // currently returns false, but will it trap in your proposal?

I propose that we do not allow this, just like we don't allow 
"2" + 2;

**Comment by martin-henz** [comment]
I hope that the type inference engines that some of the current CS4215 teams are building will be powerful enough to let students find many errors, and yet allow the usual programs (in particular all textbook programs). 

Keyword: gradual typing

**Comment by btzy** [comment]
> The trouble, I feel, is that in Chapter 3, we are introducing a mental model that makes sharing explicit: the environment model, see Section 3.3.1.

I see, in that case the current pairs with reference semantics make those linked lists much easier to use.  (I feel that it is unfortunate that pairs will have to embody two orthogonal concepts - the product type (ADT), and the reference semantics (sharing), but it is probably the simplest way.)

**Comment by martin-henz** [comment]
Specs are updated in https://github.com/source-academy/js-slang/pull/401

**Comment by martin-henz** [comment]
This proposal will also resolve https://github.com/source-academy/js-slang/issues/340

**Comment by martin-henz** [comment]
As discussed in the "SA 2021 js-slang" group, the new definition of the `equal` function is a bit of a mouthful:
```function equal(xs, ys) {
    return is_pair(xs)
        ? (is_pair(ys) &amp;&amp;
           equal(head(xs), head(ys)) &amp;&amp; 
           equal(tail(xs), tail(ys)))
        : is_null(xs)
        ? is_null(ys)
        : is_number(xs)
        ? (is_number(ys) &amp;&amp; xs === ys)
        : is_boolean(xs)
        ? (is_boolean(ys) &amp;&amp; ((xs &amp;&amp; ys) || (!xs &amp;&amp; !ys)))
        : is_string(xs)
        ? (is_string(xs) &amp;&amp; xs === ys)
        : is_undefined(xs)
        ? is_undefined(ys)
        : // we know now that xs is a function
          (is_function(ys) &amp;&amp; xs === ys);
}```

While this is ok as specs, we may want to have a more efficient implementation in JavaScript using typeof.
