### ISSUE TITLE
Proposal: help function

### ISSUE THREAD

**Issue by ning-y** [source-academy/js-slang#419]
A function named `help` which takes a function argument and prints the help message for that function. As in the `help` functions of python or R.

Having the function specifications accessible from the IDE itself rather than on another website may encourage students to consult the function specifications more often. Reading documentation is, of course, an important part of being a competent programmer.

This may also set an example for further external libraries to document their functions.

Suggesting because
- #399 drives source toward becoming more a fully-featured language. Talking about features, I think a `help` function would be a good one.
- I came back to source after a year and a half, and I keep forgetting if `filter` takes the function first then the list or the other way round (python takes the function first, but R takes the list first).

**Comment by btzy** [comment]
I find this proposal rather constraining, and only fits well when Source is interpreted.  Having a help function means that any conforming Source VM or compiler needs to contain the documentation text, which would bloat the implementation.  This also tightly couples the documentation text to the implementation.

I think we should look towards IDE support instead (e.g. hovering over functions names in the source code will show their documentation, I think some recent project made this work).

At most, it might still be reasonable to make `help` a magic keyword in the REPL (so if the REPL gets `help x` where `x` is a name, it will return the documentation text for `x` (or open a new tab in the browser to go to the documentation page) instead of executing the code).  So js-slang should never need to understand `help`.

**Comment by martin-henz** [comment]
I agree with @btzy : 

"Having the function specifications accessible from the IDE itself rather than on another website may encourage students to consult the function specifications more often. Reading documentation is, of course, an important part of being a competent programmer."

This objective is served by the new auto-complete and library lookup functionality of the Source Academy.
