### ISSUE TITLE
temporal dead zone

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#61]
Currently, this program (Textbook 1.3.2) works, but should not, according to JavaScript's "temporal dead zone" TDZ:

function h() {
    const x = 1;
    function i() {
        const x = x + 1;
        return x;
    }
    return i();
}
h();

**Comment by ningyuansg** [comment]
The temporal dead zone in ES6 is a result of const/let hoisting. 

The program above works when it shouldn't because source does not have this temporal dead zone, because we do not hoist const and let declarations.

So, if we fix const/let hoisting, it is equivalent to fixing this bug (where the TDZ is not there, but should be there).

Hosting const/let is already an open issue at #38. Will close in favour of that, since #38 address TDZ closer to the source of the problem, which is const/let hoisting.
