### ISSUE TITLE
Type inference: dereferences undefined value when formatting error created when a non-function is applied

### ISSUE THREAD

**Issue by Aulud** [source-academy/js-slang#627]
## [Bug] Playground editor stalls for some Source programs
Editor or interpreter-related bug.

### Bug description
Attempting to run the following (incorrect) Source program in the Playground **more than once** results in the Source interpreter stalling and locking up the editor. This occurs on all chapters of Source and appears to not be affected by the selected library.

![image](https://user-images.githubusercontent.com/44989315/83447299-cc638780-a482-11ea-9804-aaccf68ed80c.png)

The bug does not occur in assessments.

### Replication instructions
1. Proceed to the Source Academy playground with this program [here](https://api2.sourceacademy.nus.edu.sg/1l)
2. Click the `Run` button/Press Shift-Enter twice to evaluate the program twice

Last updated 2 June 2020, 3:30AM

**Comment by angelsl** [comment]
Transferred the issue from cadet-frontend.

**Comment by angelsl** [comment]
I've traced the issue. It is not a frontend issue; it's a bug in js-slang, [here](https://github.com/source-academy/js-slang/blob/c1317ba171c37ff462a01ddc17c8b7f68061e0ab/src/typeChecker/typeChecker.ts#L791-L793)&mdash;specifically this line:

```ts
const expectedTypes = (calledFunctionType as FunctionType).parameterTypes
```

When a non-function is applied, a UnifyError is raised there, but the error handler assumes `calledFunctionType` is a function type (expressed in the `as` cast), and then creates an `InvalidArgumentTypesError` with `expectedTypes = calledFunctionType.parameterTypes`, which is `undefined` since `calledFunctionType` is not a function type.

![image](https://user-images.githubusercontent.com/235432/83449408-26198100-a486-11ea-9ada-f338e03a0598.png)

Later, when the frontend calls `parseError` (a js-slang function that formats the errors for human reading), `parseError` expects `expectedTypes` to be an array (following the type signature) and dereferences its `length`, but it is actually `undefined`.

(@Aulud points out that this bug is very ironic.)

**Comment by martin-henz** [comment]
haha
