### ISSUE TITLE
Operators === and !== for undefined and booleans

### ISSUE THREAD

**Issue by btzy** [source-academy/js-slang#724]
For some reason, I had not noticed the inconsistency in #389 where the fix limited `===` and `!==` to numbers and strings only for Source §1 and §2.  On hindsight, I think we should have supported it for booleans too, and optionally for undefined (where `a === b` should trivially return `true`).  However, both operators should still trap if the two arguments are of different types.

**Why support it for booleans:** They are "value types", just like numbers.  Writing `(xs && ys) || (!xs && !ys)` is not as concise, and is fairly error-prone.  We don't want that verbosity to become "idiomatic Source".

**Why support it for both booleans and undefined:** We do not face the reference semantics issue raised in #389, which was the original motivation for the chage.  Furthermore, supporting this makes it easier to write generic code: for example, the `member()`, `remove()` and `remove_all()` functions won't currently work with booleans and undefined, which is surprising.  Alternatively, we may argue that limiting `===` and `!==` to _only_ numbers and strings suggests that they are somehow more "privileged" than booleans and undefined, and this is probably not desirable.

**Comment by martin-henz** [comment]
Let's go to the source of Source: SICP. In SICP, there are =, eq? and equal?. (Scheme has several other procedures denoting some sort of equality, such as eqv?, symbol=?, boolean=? etc.) The Scheme procedure = is used only on numbers in SICP and the Scheme procedure eq? is used in chapters 1 and 2 only on symbols. In SICP JS, we use strings to represent Scheme's symbols. JavaScript's === can handle numbers and strings, so in our adaptation it was natural to use === for = and eq?. We could have introduced is_equal_number and is_equal_string, to follow the textbook more closely, but we didn't, in order to keep the look and feel of JavaScript. We could have allowed === on boolean values, undefined (and perhaps also null) in chapters 1 and 2 and still retain a strong notion of referential transparency. Your question is then: why not?

(1) Because we didn't have to

The languages Source §x follow the SICP chapters. Whatever concept is covered in the chapter needs to be supported by the language. We try to keep the languages as simple as possible, so in reverse, whatever is not covered in the chapter shouldn't be in the language. The operators = and eq? are only used on numbers and symbols, respectively, in chapters 1 and 2, and thus === should only work on numbers and strings. Boolean equivalence doesn't seem to be used in our programs. Equality on undefined is quite useless if it gives an error when the other argument is not undefined. (There is also is_undefined.)

(2) Because other operators already have the number/string overloading: +, >, <, >=, <=

There is minimal cognitive load making === and !== have the same signature as those other overloaded operators. The type table for Source §1 and §2 is neater this way.

(3) Because === on booleans is abused by students

Beginners often don't fully understand booleans and conditionals and write programs like this:
<some predicate> === true ? <a> : <b> when they should write <some predicate> ? <a> : <b> or they write
<some predicate> === false ? <a> : <b> when they should write <some predicate> ? <b> : <a>.
Up to now, we needed to tell the Avengers to look out for this idiom and correct it. This year, the restriction of === gently nudges the students on the right path.

**Comment by btzy** [comment]
I agree with (3), am neutral to (1), but disagree with (2).

For (2):  Since there are also number-only operators (-, *, /, %) and boolean-only operators (!, &&, ||), there isn't really anything special about those operators with number/string overloading.  We also have a precedent for operators that can take any type - the RHS argument of && and || are allowed to have any type.  If anything, allowing === for booleans highlights the relationship between equivalence relations and total orderings - that any total ordering must give rise to an equivalence relation.

For (1):  It's reasonable that === shouldn't need to work for booleans because it is not covered in the SICP chapter.  But taken together with Source §3 and §4, we would now need a reason to turn on boolean and undefined for === in Source §3+, in addition to the introduction of referential equality (which is only sufficient as a reason to turn on === for pairs.  Both ways seem to be imperfect here.

**Comment by martin-henz** [comment]
Your last sentence under (2) is an argument in my favour: The total order on numbers induced by < and <= gives rise an equivalence relation on numbers, and the total order on strings induced by < and <= gives rise to an equivalence relation on strings. So there is a natural connection between === and <,<=<,>,>=, and allowing booleans as arguments of === would muddy this relationship, because < is not defined on booleans.

**Comment by btzy** [comment]
I meant to say that having === for booleans will highlight that "any total ordering must give rise to an equivalence relation, but not necessarily the other way round", so it would be a one-way implication.  The one-way-ness of the implication is emphasised if we have === for booleans.

The argument about === being upgraded for pointer equality seems reasonable to me.

**Comment by martin-henz** [comment]
To summarize: It's a bit of a judgment call. I think we're good with the status quo.
